[package]
name = "warroom-hook"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
awr-i18n.workspace = true
awr-wire.workspace = true
awr-procs.workspace = true
serde_json.workspace = true


[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Pipes", "Win32_System_Threading"] }
