//! Read model consumed by the front end. Exported to TS with `ts-rs` (`cargo test -p awr-application`).

use crate::locale;
use crate::ports::{QuestionOption, QuestionPrompt, TranscriptSummary, Usage};
use awr_domain::{Attention, Session, SessionId, SessionStatus, Timestamp, WaitReason, WarRoom};
use serde::Serialize;
use std::collections::{BTreeMap, HashMap, HashSet};
use ts_rs::TS;

/// Same urgency order as `Attention`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum AttentionView {
    Offline,
    Idle,
    Working,
    Finished,
    NeedsYou,
}

impl From<Attention> for AttentionView {
    fn from(a: Attention) -> Self {
        match a {
            Attention::Offline => Self::Offline,
            Attention::Idle => Self::Idle,
            Attention::Working => Self::Working,
            Attention::Finished => Self::Finished,
            Attention::NeedsYou => Self::NeedsYou,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct WarRoomView {
    pub aggregate: AttentionView,
    pub rooms: Vec<RoomView>,
    /// Tokens and estimated cost of every known session today.
    pub today: UsageView,
}

/// A working session with no activity for this long is flagged as possibly stuck.
pub const STALL_AFTER_MS: i64 = 6 * 60 * 1000;

/// While a shell command runs, silence is expected (builds, test suites), so it waits longer.
pub const COMMAND_STALL_AFTER_MS: i64 = 30 * 60 * 1000;

/// Shell tool names as each provider reports them in its hooks.
const SHELL_TOOLS: &[&str] = &["Bash", "Shell", "PowerShell", "run_command"];

#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct UsageView {
    #[ts(type = "number")]
    pub input_tokens: u64,
    #[ts(type = "number")]
    pub output_tokens: u64,
    #[ts(type = "number")]
    pub cache_read_tokens: u64,
    #[ts(type = "number")]
    pub cache_write_tokens: u64,
    #[ts(type = "number")]
    pub total_tokens: u64,
    /// Estimated at API prices; subscriptions don't pay this, but it compares sessions.
    pub cost_usd: f64,
    /// Some messages used a model without a known price.
    pub partial_cost: bool,
}

impl From<&Usage> for UsageView {
    fn from(u: &Usage) -> Self {
        Self {
            input_tokens: u.input_tokens,
            output_tokens: u.output_tokens,
            cache_read_tokens: u.cache_read_tokens,
            cache_write_tokens: u.cache_write_tokens,
            total_tokens: u.tokens(),
            cost_usd: u.cost_micros as f64 / 1_000_000.0,
            partial_cost: u.unpriced_messages > 0,
        }
    }
}

/// On-demand "what did it change": files it edited and commits made in its worktree meanwhile.
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct SessionChanges {
    pub worktree: String,
    pub files: Vec<TouchedFileView>,
    pub commits: Vec<CommitView>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct TouchedFileView {
    /// Relative to the worktree when inside it.
    pub path: String,
    pub edits: u32,
    pub written: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct CommitView {
    pub hash: String,
    pub short: String,
    pub subject: String,
    pub author: String,
    #[ts(type = "number")]
    pub at: i64,
    pub files_changed: u32,
    pub insertions: u32,
    pub deletions: u32,
}

/// One room per repository.
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct RoomView {
    pub repo_id: String,
    pub repo_name: String,
    pub attention: AttentionView,
    pub sessions: Vec<SessionView>,
}

#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct SessionView {
    pub id: String,
    pub provider: String,
    pub attention: AttentionView,
    /// Short on-screen phrase (UI copy): the current tool, a permission request, "your turn"…
    pub status_label: String,
    /// Title generated by the agent; `null` until it writes one.
    pub title: Option<String>,
    /// The task the session started with.
    pub first_prompt: Option<String>,
    /// How the agent was launched (`claude --resume …`).
    pub command: Option<String>,
    pub last_prompt: Option<String>,
    pub last_reply: Option<String>,
    pub last_action: Option<String>,
    pub model: Option<String>,
    /// Reasoning effort of the last turn.
    pub effort: Option<String>,
    #[ts(type = "number | null")]
    pub context_tokens: Option<u64>,
    /// Context window of the current model, to show how full it is.
    #[ts(type = "number | null")]
    pub context_window: Option<u64>,
    pub usage: UsageView,
    /// Working but silent since this moment (ms) for longer than [`STALL_AFTER_MS`] (or
    /// [`COMMAND_STALL_AFTER_MS`] while a shell command runs): maybe stuck.
    #[ts(type = "number | null")]
    pub stalled_since: Option<i64>,
    pub worktree_path: String,
    pub branch: Option<String>,
    pub is_linked_worktree: bool,
    pub subagents: Vec<SubagentView>,
    /// Skills used, most recent first.
    pub skills: Vec<SkillView>,
    pub turns: u32,
    #[ts(type = "number")]
    pub started_at: i64,
    #[ts(type = "number")]
    pub last_activity_at: i64,
    #[ts(type = "number")]
    pub status_since: i64,
    pub archived: bool,
    pub muted: bool,
    pub alive: bool,
    pub terminal: Option<String>,
    pub tmux_pane: Option<String>,
    /// There is a direct link to the Warp pane.
    pub in_warp: bool,
    /// The app's own terminal: can be viewed and typed into from here.
    pub pty_id: Option<String>,
    /// There is a pending permission that can be approved or denied from the app.
    pub can_approve: bool,
    /// The agent is waiting for an answer to a question (not a permission decision).
    pub awaiting_question: bool,
    /// The question text when the provider included it in the hook payload.
    pub pending_question: Option<String>,
    /// A live hook is waiting for answers from this app.
    pub can_answer_question: bool,
    /// Structured questions and choices from that hook.
    pub questions: Vec<QuestionView>,
    /// Files this session edited that another live session in the same worktree edited too.
    pub shared_files: Vec<SharedFileView>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct QuestionView {
    pub question: String,
    pub header: Option<String>,
    pub options: Vec<QuestionOptionView>,
    pub multi_select: bool,
}

impl From<&QuestionPrompt> for QuestionView {
    fn from(prompt: &QuestionPrompt) -> Self {
        Self {
            question: prompt.question.clone(),
            header: prompt.header.clone(),
            options: prompt.options.iter().map(QuestionOptionView::from).collect(),
            multi_select: prompt.multi_select,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct QuestionOptionView {
    pub label: String,
    pub description: Option<String>,
}

impl From<&QuestionOption> for QuestionOptionView {
    fn from(option: &QuestionOption) -> Self {
        Self { label: option.label.clone(), description: option.description.clone() }
    }
}

/// A file two live sessions of the same worktree both edited: one may overwrite the other's work.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct SharedFileView {
    /// Relative to the worktree when it is inside it.
    pub path: String,
    /// The other sessions that edited it.
    pub sessions: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct SubagentView {
    pub id: String,
    pub kind: Option<String>,
    pub description: Option<String>,
    pub last_tool: Option<String>,
    pub model: Option<String>,
    pub effort: Option<String>,
    pub running: bool,
    #[ts(type = "number")]
    pub started_at: i64,
    #[ts(type = "number | null")]
    pub finished_at: Option<i64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum SkillSourceView {
    Project,
    Personal,
    Plugin,
    Builtin,
}

impl From<awr_domain::SkillSource> for SkillSourceView {
    fn from(s: awr_domain::SkillSource) -> Self {
        use awr_domain::SkillSource;
        match s {
            SkillSource::Project => Self::Project,
            SkillSource::Personal => Self::Personal,
            SkillSource::Plugin => Self::Plugin,
            SkillSource::Builtin => Self::Builtin,
        }
    }
}

/// A skill used in the session: who invoked it and where it comes from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct SkillView {
    pub name: String,
    pub source: SkillSourceView,
    pub by_user: bool,
    pub by_agent: bool,
    pub count: u32,
    #[ts(type = "number")]
    pub last_at: i64,
}

/// Subagent preview: what it was asked, what it answered and what it did along the way.
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct SubagentPreview {
    pub session_id: String,
    pub agent: SubagentView,
    pub first_prompt: Option<String>,
    pub last_reply: Option<String>,
    pub timeline: Vec<TimelineEntryView>,
}

/// Session preview: its card and the recent conversation.
#[derive(Debug, Clone, PartialEq, Serialize, TS)]
#[ts(export)]
pub struct SessionDetail {
    pub session: SessionView,
    pub timeline: Vec<TimelineEntryView>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct TimelineEntryView {
    /// "prompt" (you), "reply" (the agent, Markdown) or "tool" (tool use summary).
    pub kind: TimelineKindView,
    pub text: String,
    #[ts(type = "number | null")]
    pub at: Option<i64>,
    pub model: Option<String>,
    pub effort: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(export)]
pub enum TimelineKindView {
    Prompt,
    Reply,
    Tool,
}

impl From<crate::ports::TimelineItem> for TimelineEntryView {
    fn from(item: crate::ports::TimelineItem) -> Self {
        use crate::ports::TimelineKind;
        Self {
            kind: match item.kind {
                TimelineKind::Prompt => TimelineKindView::Prompt,
                TimelineKind::Reply => TimelineKindView::Reply,
                TimelineKind::Tool => TimelineKindView::Tool,
            },
            text: item.text,
            at: item.at,
            model: item.model,
            effort: item.effort,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[ts(export)]
pub struct IntegrationStatus {
    /// `claude`, `codex`…
    pub provider: String,
    /// The agent's configuration folder exists (it is installed on this machine).
    pub agent_found: bool,
    /// The app can start and resume this agent (Antigravity only runs inside its own app).
    pub launchable: bool,
    pub installed: bool,
    /// Hook events pointing at our bridge.
    pub hooked_events: Vec<String>,
    pub settings_path: String,
    pub bridge_path: String,
    pub bridge_present: bool,
}

pub fn project(
    room: &WarRoom,
    summaries: &HashMap<SessionId, TranscriptSummary>,
    approvable: &HashSet<SessionId>,
    now: Timestamp,
) -> WarRoomView {
    let mut by_repo: BTreeMap<String, RoomView> = BTreeMap::new();
    for session in room.sessions() {
        let entry = by_repo.entry(session.workspace.repo.0.clone()).or_insert_with(|| RoomView {
            repo_id: session.workspace.repo.0.clone(),
            repo_name: session.workspace.repo_name.clone(),
            attention: AttentionView::Offline,
            sessions: Vec::new(),
        });
        entry.sessions.push(session_view(session, summaries.get(&session.id), approvable.contains(&session.id), now));
    }
    let mut shared = shared_files(room, summaries);
    for view in by_repo.values_mut().flat_map(|r| r.sessions.iter_mut()) {
        view.shared_files = shared.remove(&SessionId(view.id.clone())).unwrap_or_default();
    }

    let mut rooms: Vec<RoomView> = by_repo
        .into_values()
        .map(|mut r| {
            r.sessions.sort_by_key(|s| (std::cmp::Reverse(s.attention), std::cmp::Reverse(s.last_activity_at)));
            r.attention = r
                .sessions
                .iter()
                .filter(|s| !s.archived && !s.muted)
                .map(|s| s.attention)
                .max()
                .unwrap_or(AttentionView::Offline);
            r
        })
        .collect();
    rooms.sort_by(|a, b| b.attention.cmp(&a.attention).then_with(|| a.repo_name.cmp(&b.repo_name)));

    let mut today = Usage::default();
    for summary in summaries.values() {
        today.add(&summary.usage_today);
    }
    let aggregate = rooms.iter().map(|r| r.attention).max().unwrap_or(AttentionView::Offline);
    WarRoomView { aggregate, rooms, today: (&today).into() }
}

/// Files edited by more than one live, not archived session of the same worktree, per session.
/// Separate worktrees never clash: that is the way out this nudges towards.
pub(crate) fn shared_files(
    room: &WarRoom,
    summaries: &HashMap<SessionId, TranscriptSummary>,
) -> HashMap<SessionId, Vec<SharedFileView>> {
    // (worktree, absolute path) → sessions that edited it.
    let mut editors: BTreeMap<(&str, String), Vec<&SessionId>> = BTreeMap::new();
    for s in room.sessions().filter(|s| s.is_alive() && !s.archived) {
        let worktree = s.workspace.worktree_path.as_str();
        for file in summaries.get(&s.id).into_iter().flat_map(|x| &x.edited_files) {
            let absolute = if file.starts_with('/') { file.clone() } else { format!("{worktree}/{file}") };
            editors.entry((worktree, absolute)).or_default().push(&s.id);
        }
    }
    let mut out: HashMap<SessionId, Vec<SharedFileView>> = HashMap::new();
    for ((worktree, file), ids) in editors.into_iter().filter(|(_, ids)| ids.len() > 1) {
        let path = file.strip_prefix(worktree).and_then(|p| p.strip_prefix('/')).unwrap_or(&file).to_owned();
        for id in &ids {
            let sessions = ids.iter().filter(|o| o != &id).map(|o| o.0.clone()).collect();
            out.entry((*id).clone()).or_default().push(SharedFileView { path: path.clone(), sessions });
        }
    }
    out
}

/// A completed main turn still owns any commands running in the background.
pub(crate) fn effective_attention(s: &Session, summary: Option<&TranscriptSummary>) -> Attention {
    let attention = s.attention();
    if matches!(s.status, SessionStatus::AwaitingYou { reason: WaitReason::Permission, .. })
        && summary.is_some_and(|s| s.automatic_permission_review)
    {
        return Attention::Working;
    }
    if matches!(attention, Attention::Idle | Attention::Finished)
        && summary.is_some_and(|summary| summary.running_commands > 0)
    {
        Attention::Working
    } else {
        attention
    }
}

/// When a working session went silent, if it has been silent long enough to look stuck.
pub fn stalled_since(s: &Session, now: Timestamp) -> Option<i64> {
    let after = match &s.status {
        SessionStatus::Working { tool: Some(tool) } if SHELL_TOOLS.contains(&tool.as_str()) => COMMAND_STALL_AFTER_MS,
        SessionStatus::Working { .. } | SessionStatus::Compacting => STALL_AFTER_MS,
        _ => return None,
    };
    (now.0 - s.last_activity_at.0 >= after).then_some(s.last_activity_at.0)
}

pub(crate) fn session_view(
    s: &Session,
    summary: Option<&TranscriptSummary>,
    can_approve: bool,
    now: Timestamp,
) -> SessionView {
    let summary = summary.cloned().unwrap_or_default();
    let detail = |id: &str| summary.subagents.iter().find(|d| d.id == id).cloned().unwrap_or_default();
    let (awaiting_question, pending_question) = match &s.status {
        SessionStatus::AwaitingYou { reason: WaitReason::Question, detail, .. } => (true, detail.clone()),
        _ => (false, None),
    };
    let mut view = SessionView {
        id: s.id.0.clone(),
        provider: format!("{:?}", s.provider).to_lowercase(),
        attention: effective_attention(s, Some(&summary)).into(),
        status_label: if effective_attention(s, Some(&summary)) == Attention::Working
            && matches!(
                s.status,
                SessionStatus::Idle | SessionStatus::AwaitingInput | SessionStatus::AwaitingYou { .. }
            ) {
            locale::status_thinking().into()
        } else {
            status_label(s)
        },
        title: summary.title.clone(),
        first_prompt: summary.first_prompt.clone(),
        command: s.host.agent_command.as_deref().map(readable_command),
        last_prompt: summary.last_prompt.clone(),
        last_reply: summary.last_reply.clone(),
        last_action: summary.last_action.clone(),
        model: summary.model.clone(),
        effort: summary.effort.clone(),
        context_tokens: summary.context_tokens,
        context_window: summary.context_window,
        usage: (&summary.usage).into(),
        stalled_since: stalled_since(s, now),
        worktree_path: s.workspace.worktree_path.clone(),
        branch: s.workspace.branch.clone(),
        is_linked_worktree: s.workspace.is_linked_worktree,
        subagents: s
            .subagents
            .values()
            .map(|a| {
                let d = detail(&a.id);
                SubagentView {
                    id: a.id.clone(),
                    kind: a.kind.clone(),
                    description: d.description,
                    // The transcript gives more detail ("Grep · pattern"); the hook, at least the name.
                    last_tool: d.last_tool.or_else(|| a.current_tool.clone()),
                    model: d.model,
                    effort: d.effort,
                    running: a.is_running(),
                    started_at: a.started_at.0,
                    finished_at: a.finished_at.map(|t| t.0),
                }
            })
            .collect(),
        skills: {
            let mut skills: Vec<SkillView> = s
                .skills
                .values()
                .map(|k| SkillView {
                    name: k.name.clone(),
                    source: k.source.into(),
                    by_user: k.by_user,
                    by_agent: k.by_agent,
                    count: k.count,
                    last_at: k.last_at.0,
                })
                .collect();
            skills.sort_by_key(|k| std::cmp::Reverse(k.last_at));
            skills
        },
        turns: s.turns,
        started_at: s.started_at.0,
        last_activity_at: s.last_activity_at.0,
        status_since: s.status_since.0,
        archived: s.archived,
        muted: s.muted,
        alive: s.is_alive(),
        terminal: terminal_name(s),
        tmux_pane: s.host.tmux_pane.clone(),
        in_warp: s.host.warp_focus_url.is_some(),
        pty_id: s.host.pty_id.clone(),
        can_approve,
        awaiting_question,
        pending_question,
        can_answer_question: false,
        questions: Vec::new(),
        shared_files: Vec::new(),
    };
    // Running ones first; within each group, in order of arrival.
    view.subagents.sort_by_key(|a| (!a.running, a.started_at));
    view
}

fn status_label(s: &Session) -> String {
    match &s.status {
        SessionStatus::Idle | SessionStatus::AwaitingInput if s.running_subagents() > 0 => {
            locale::status_thinking().into()
        }
        SessionStatus::Idle => locale::status_idle().into(),
        SessionStatus::Working { tool: Some(tool) } => tool.clone(),
        SessionStatus::Working { tool: None } => locale::status_thinking().into(),
        SessionStatus::AwaitingYou { reason: WaitReason::Permission, tool, detail } => match (tool, detail) {
            (Some(tool), Some(detail)) => locale::asks_permission_for_detail(tool, detail),
            (Some(tool), None) => locale::asks_permission_for(tool),
            _ => locale::status_asks_permission().into(),
        },
        SessionStatus::AwaitingYou { reason: WaitReason::Question, .. } => locale::status_asks_question().into(),
        SessionStatus::AwaitingInput if s.unseen => locale::status_finished().into(),
        SessionStatus::AwaitingInput => locale::status_your_turn().into(),
        SessionStatus::Compacting => locale::status_compacting().into(),
        SessionStatus::Ended { .. } => locale::status_ended().into(),
    }
}

/// First ancestor of the agent that looks like a terminal or IDE (what needs focusing).
/// The command as you would type it: `/…/vendor/…/bin/codex resume x` → `codex resume x`.
fn readable_command(command: &str) -> String {
    let (program, args) = command.split_once(' ').unwrap_or((command, ""));
    let program = program.rsplit('/').next().unwrap_or(program);
    if args.is_empty() { program.to_owned() } else { format!("{program} {args}") }
}

fn terminal_name(s: &Session) -> Option<String> {
    if let Some(program) = &s.host.term_program {
        return Some(program.clone());
    }
    const SHELLS: &[&str] = &["bash", "zsh", "fish", "sh", "dash", "claude", "node", "tmux: server", "tmux"];
    let agent = s.host.agent_pid?;
    s.host
        .ancestry
        .iter()
        .skip_while(|p| p.pid != agent)
        .skip(1)
        .find(|p| !SHELLS.contains(&p.name.as_str()))
        .map(|p| p.name.clone())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launch_commands_read_as_typed() {
        assert_eq!(
            readable_command("/home/u/.npm/vendor/x86_64/bin/codex --sandbox read-only"),
            "codex --sandbox read-only"
        );
        assert_eq!(readable_command("claude"), "claude");
    }

    #[test]
    fn a_running_shell_command_gets_longer_before_it_looks_stuck() {
        use awr_domain::{ProviderKind, RepoId, SessionContext, SessionEventKind, TerminalHost, Workspace};
        let context = SessionContext {
            provider: ProviderKind::Claude,
            workspace: Workspace {
                repo: RepoId("/repo/.git".into()),
                repo_name: "repo".into(),
                worktree_path: "/repo".into(),
                branch: None,
                is_linked_worktree: false,
            },
            host: TerminalHost::default(),
            transcript_path: None,
            cwd: None,
        };
        let mut s = Session::open(SessionId("s".into()), context, Timestamp(0));
        let after = |s: &Session, ms: i64| stalled_since(s, Timestamp(ms)).is_some();

        s.apply(None, &SessionEventKind::ToolStarted { tool: "Read".into() }, Timestamp(0));
        assert!(after(&s, STALL_AFTER_MS));

        s.apply(None, &SessionEventKind::ToolStarted { tool: "Bash".into() }, Timestamp(0));
        assert!(!after(&s, STALL_AFTER_MS), "a build or a test suite can be silent for a while");
        assert!(after(&s, COMMAND_STALL_AFTER_MS));

        s.apply(None, &SessionEventKind::ToolFinished { tool: "Bash".into(), failed: false }, Timestamp(0));
        assert!(after(&s, STALL_AFTER_MS), "thinking after the command uses the normal threshold");
    }
}
